parameters:
  name: ''
  vmImage: ''

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        p38:
          python.version: '3.8'
        py310:
          python.version: '3.10'
        py312:
          python.version: '3.12'
      maxParallel: 2
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        name: set_py_ver
      - script: |
          python -V
          pip install -e .[dev]
          pip freeze
        name: requirements
      - script: pytest
        name: test
