trigger:
  - master

jobs:
  - template: azure-pybuild.yml
    parameters:
      name: Win
      vmImage: 'vs2017-win2016'

  - template: azure-pybuild.yml
    parameters:
      name: WinCo
      vmImage: 'windows-2019'

  - template: azure-pybuild.yml
    parameters:
      name: macOS
      vmImage: 'macOS-10.14'

  - template: azure-pybuild.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-16.04'


  - job: Check
    dependsOn:
      - WinCo
      - Win
      - macOS
      - Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          architecture: 'x64'
      - script: |
          pip install -e .[dev]
          python setup.py sdidt bdist_wheel
        name: dist
      - script: |
          python -m twine check dist/*