trigger:
  - master

jobs:
  - template: azure-pybuild.yml
    parameters:
      name: Win
      vmImage: 'windows-latest'

  - template: azure-pybuild.yml
    parameters:
      name: Win2019
      vmImage: 'windows-2019'

  - template: azure-pybuild.yml
    parameters:
      name: macOS
      vmImage: 'macOS-latest'

  - template: azure-pybuild.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-latest'


  - job: Check
    dependsOn:
      - Win2019
      - Win
      - macOS
      - Linux
    pool:
      vmImage: 'ubuntu-lastest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          architecture: 'x64'
      - script: |
          pip install -e .[dev]
          python setup.py sdidt bdist_wheel
        name: dist
      - script: |
          python -m twine check dist/*